CREATE TABLE member (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	number VARCHAR(50) NOT NULL UNIQUE,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	regist_time DATETIME,
	last_login_time DATETIME,
	last_login_ip VARCHAR(50),
	is_enable BIT(2),
	sort_id DOUBLE(20,2),
	pay_password VARCHAR(50),
	nickname VARCHAR(50),
	head_img VARCHAR(50),
	identity VARCHAR(50),
	sex CHAR(2),
	age INTEGER(10),
	mobile VARCHAR(50),
	email VARCHAR(50),
	real_name VARCHAR(50),
	birthday DATETIME,
	balance DOUBLE(20,2),
	forst_balance DOUBLE(20,2),
	total_consume DOUBLE(20,2),
	level_number VARCHAR(50)
)ENGINE=MyISAM DEFAULT CHARSET=utf8
