CREATE TABLE member_level (
	id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	number VARCHAR(50) NOT NULL UNIQUE,
	title VARCHAR(50) NOT NULL,
	rank BIGINT(20),
	is_default BIT(2),
	sort_id DOUBLE(20,2),
	required DOUBLE(20,2)
)ENGINE=MYISAM DEFAULT CHARSET=utf8;